# github.com/go-task/task

version: '2'

vars:
  PG_USER: postgres
  PG_PASSWORD: HhmL0SWLuxPirhQO9dXD
  PG_HOST: rpcs.cvsc3wzxbc5v.us-west-2.rds.amazonaws.com
  DB_NAME: engine_db
  DUMP_FILE: database/database/seeds/init_engine_db.sql

tasks:
  drop-db:
    desc: Drop the engine_db
    cmds: 
      - |
        PGPASSWORD={{.PG_PASSWORD}} dropdb --host {{.PG_HOST}} -U {{.PG_USER}} {{.DB_NAME}} &&
        PGPASSWORD={{.PG_PASSWORD}} psql --host {{.PG_HOST}} -U {{.PG_USER}} -c 'CREATE DATABASE {{.DB_NAME}};'

  restore-db:
    desc: Restore the engine_db
    cmds: 
      - |
        PGPASSWORD={{.PG_PASSWORD}} psql --host {{.PG_HOST}} -U {{.PG_USER}} -d {{.DB_NAME}} < database/database/seeds/init_engine_db.sql

  dump-db:
    desc: Dump the engine_db
    cmds: 
      - |
        PGPASSWORD={{.PG_PASSWORD}} pg_dump -v --host {{.PG_HOST}} -U {{.PG_USER}} -d {{.DB_NAME}} --schema-only --file=database/database/seeds/init_engine_db.sql

  dump-data:
    desc: Dump the engine_db
    cmds: 
      - |
        PGPASSWORD={{.PG_PASSWORD}} pg_dump -v --host {{.PG_HOST}} -U {{.PG_USER}} -d {{.DB_NAME}} --file=database/database/seeds/engine_db_data.sql
  
  seed-test-data:
    desc: Seeds local postgres database with test data
    cmds:
      - |
        PGPASSWORD={{.PG_PASSWORD}} psql --host {{.PG_HOST}} -U {{.PG_USER}} -d {{.DB_NAME}} < database/database/seeds/test_data.sql

  run-tests:
    desc: Run the tests to exercise the database API
    cmds:
      - task: drop-db
      - task: restore-db
      - task: seed-test-data
      - pytest database/tests/

  drop-db-local:
    desc: Drop the engine_db
    cmds: 
      - |
        PGPASSWORD={{.LOCAL_PG_PASSWORD}} dropdb --host {{.LOCAL_PG_HOST}} -U {{.LOCAL_PG_USER}} {{.LOCAL_DB_NAME}} &&
        PGPASSWORD={{.LOCAL_PG_PASSWORD}} psql --host {{.LOCAL_PG_HOST}} -U {{.LOCAL_PG_USER}} -c 'CREATE DATABASE {{.LOCAL_DB_NAME}};'

  restore-db-local:
    desc: Restore the engine_db
    cmds: 
      - |
        PGPASSWORD={{.LOCAL_PG_PASSWORD}} psql --host {{.LOCAL_PG_HOST}} -U {{.LOCAL_PG_USER}} -d {{.LOCAL_DB_NAME}} < database/database/seeds/init_engine_db.sql

  dump-db-local:
    desc: Dump the engine_db
    cmds: 
      - |
        PGPASSWORD={{.LOCAL_PG_PASSWORD}} pg_dump -v --host {{.LOCAL_PG_HOST}} -U {{.LOCAL_PG_USER}} -d {{.LOCAL_DB_NAME}} --schema-only --file=database/database/seeds/init_engine_db.sql

  seed-test-data-local:
    desc: Seeds local postgres database with test data
    cmds:
      - |
        PGPASSWORD={{.LOCAL_PG_PASSWORD}} psql --host {{.LOCAL_PG_HOST}} -U {{.LOCAL_PG_USER}} -d {{.LOCAL_DB_NAME}} < database/database/seeds/test_data.sql

  run-tests-local:
    desc: Run the tests to exercise the database API
    cmds:
      - task: drop-db-local
      - task: restore-db-local
      - task: seed-test-data-local
      - pytest database/tests/
