# github.com/go-task/task

version: '2'

vars:
  PG_USER: postgres
  PG_PASSWORD: admin
  PG_HOST: localhost
  DB_NAME: engine_db
  DUMP_FILE: seeds/init_engine_db.sql

tasks:
  drop-db:
    desc: Drop the engine_db
    cmds: 
      - |
        PGPASSWORD={{.PG_PASSWORD}} dropdb --host {{.PG_HOST}} -U {{.PG_USER}} {{.DB_NAME}} &&
        PGPASSWORD={{.PG_PASSWORD}} psql --host {{.PG_HOST}} -U {{.PG_USER}} -c 'CREATE DATABASE {{.DB_NAME}};'

  restore-db:
    desc: Restore the engine_db
    cmds: 
      - |
        PGPASSWORD={{.PG_PASSWORD}} psql --host {{.PG_HOST}} -U {{.PG_USER}} -d {{.DB_NAME}} < seeds/init_engine_db.sql

  dump-db:
    desc: Dump the engine_db
    cmds: 
      - |
        PGPASSWORD={{.PG_PASSWORD}} pg_dump -v --host {{.PG_HOST}} -U {{.PG_USER}} -d {{.DB_NAME}} --schema-only --file=seeds/init_engine_db.sql